site_name: Autogitter
site_description: Git repository synchronization tool
site_url: https://arch-err.github.io/autogitter

repo_name: arch-err/autogitter
repo_url: https://github.com/arch-err/autogitter

theme:
  name: terminal
  palette: gruvbox_dark
  favicon: assets/logo.jpg
  features:
    - navigation.side.indexes

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - tables
  - attr_list

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
